version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: fitness-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: fitness_db
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p123456"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build: ./fitness-tracker-backend
    container_name: fitness-backend
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fitness_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456

  frontend:
    build: ./fitness-tracker-frontend
    container_name: fitness-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data: